package vista;

import controlador.AfiliadoData;
import controlador.OrdenData;
import controlador.PrestadorData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Afiliado;
import modelo.Orden;
import modelo.Prestador;

public class VistaVerOrdenes extends javax.swing.JFrame {

    OrdenData orden_data = new OrdenData();
    AfiliadoData afiliado_data = new AfiliadoData();
    PrestadorData prestador_data = new PrestadorData();
    private final DefaultTableModel modelo;

    public VistaVerOrdenes() {
        initComponents();
        setResizable(false);
        ButtonGroup grupoDeBotones = new ButtonGroup();
        grupoDeBotones.add(radio_mostrarPorAfiliado);
        grupoDeBotones.add(radio_mostrarPorPrestador);
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {

                return column != 0;

            }

        };

        armarCabecera();
    }

    private void armarCabecera() {

        ArrayList<Object> cabecera = new ArrayList<>();
        cabecera.add("ID");
        cabecera.add("Fecha");
        cabecera.add("Forma de Pago");
        cabecera.add("Importe");
        cabecera.add("Afiliado");
        cabecera.add("Prestador");

        for (Object lector : cabecera) {

            modelo.addColumn(lector);

        }

        table_ordenes.setModel(modelo);
    }

    private void borrarFilas() {

        int rowCount = modelo.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {

            modelo.removeRow(i);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        button_atras = new javax.swing.JButton();
        button_salir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ordenes = new javax.swing.JTable();
        radio_mostrarPorPrestador = new javax.swing.JRadioButton();
        radio_mostrarPorAfiliado = new javax.swing.JRadioButton();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        button_eliminarOrden = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        jDateChooser_fecha = new com.toedter.calendar.JDateChooser();
        button_ordenesPorFecha = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();
        txt_Afiliado_Prestador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("MasSalud");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 230, 10));

        button_atras.setBackground(new java.awt.Color(255, 255, 255));
        button_atras.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        button_atras.setForeground(new java.awt.Color(51, 51, 51));
        button_atras.setText("Atras");
        button_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_atrasActionPerformed(evt);
            }
        });
        getContentPane().add(button_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 60));

        button_salir.setBackground(new java.awt.Color(255, 255, 255));
        button_salir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        button_salir.setForeground(new java.awt.Color(51, 51, 51));
        button_salir.setText("Salir");
        button_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_salirActionPerformed(evt);
            }
        });
        getContentPane().add(button_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 90, 60));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Informacion de Ordenes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 230, 10));

        jSeparator6.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 140, 800, 10));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Listado de Ordenes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 230, 10));

        table_ordenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "F . De Pago", "Importe", "Afiliado", "Prestador"
            }
        ));
        jScrollPane1.setViewportView(table_ordenes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 620, 380));

        radio_mostrarPorPrestador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radio_mostrarPorPrestador.setForeground(new java.awt.Color(102, 102, 102));
        radio_mostrarPorPrestador.setText("Por Prestador");
        radio_mostrarPorPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_mostrarPorPrestadorActionPerformed(evt);
            }
        });
        getContentPane().add(radio_mostrarPorPrestador, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        radio_mostrarPorAfiliado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        radio_mostrarPorAfiliado.setForeground(new java.awt.Color(102, 102, 102));
        radio_mostrarPorAfiliado.setText("Por Afiliado");
        radio_mostrarPorAfiliado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_mostrarPorAfiliadoActionPerformed(evt);
            }
        });
        getContentPane().add(radio_mostrarPorAfiliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 150, 10));

        jSeparator12.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 150, 10));

        button_eliminarOrden.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button_eliminarOrden.setForeground(new java.awt.Color(102, 102, 102));
        button_eliminarOrden.setText("Eliminar Orden");
        button_eliminarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_eliminarOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(button_eliminarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 150, 60));

        jSeparator13.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 150, 20));
        getContentPane().add(jDateChooser_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 150, 30));

        button_ordenesPorFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        button_ordenesPorFecha.setForeground(new java.awt.Color(102, 102, 102));
        button_ordenesPorFecha.setText("Ir a Fecha");
        button_ordenesPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ordenesPorFechaActionPerformed(evt);
            }
        });
        getContentPane().add(button_ordenesPorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 150, 40));

        jSeparator14.setForeground(new java.awt.Color(153, 204, 255));
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 150, 10));

        txt_Afiliado_Prestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Afiliado_PrestadorActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Afiliado_Prestador, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 150, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Afiliado/Prestador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 140, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_atrasActionPerformed
        VistaOrden orden = new VistaOrden();
        orden.setVisible(true);
        dispose();
    }//GEN-LAST:event_button_atrasActionPerformed

    private void button_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_salirActionPerformed
        dispose();
    }//GEN-LAST:event_button_salirActionPerformed

    private void txt_Afiliado_PrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Afiliado_PrestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Afiliado_PrestadorActionPerformed

    private void radio_mostrarPorAfiliadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_mostrarPorAfiliadoActionPerformed

        try {
            Afiliado afiliado_Encontrado = afiliado_data.buscarAfiliado_dni(Integer.valueOf(txt_Afiliado_Prestador.getText()));

            borrarFilas();

            ArrayList<Orden> listadoDeOrdenes_porAfiliado = orden_data.Orden_SacadasPorAfiliado(afiliado_Encontrado.getIdAfiliado());
            for (Orden ordenes : listadoDeOrdenes_porAfiliado) {

                modelo.addRow(new Object[]{ordenes.getIdOrden(), ordenes.getFecha(), ordenes.getFormaPago(), ordenes.getImporte(), ordenes.getAfiliado().getIdAfiliado(), ordenes.getPrestador().getIdPrestador()});
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(null, "¡Debe ingresar DNI del afiliado activo!");
        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(null, "¡Debe ingresar DNI del afiliado!");
        }
    }//GEN-LAST:event_radio_mostrarPorAfiliadoActionPerformed

    private void radio_mostrarPorPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_mostrarPorPrestadorActionPerformed

        try {
            Prestador prestador_Encontrado = prestador_data.buscarPrestadorApellido(String.valueOf(txt_Afiliado_Prestador.getText()));

            borrarFilas();

            ArrayList<Orden> listadoDeOrdenes_porPrestador = orden_data.Orden_SacadasSegunPrestador(prestador_Encontrado.getIdPrestador());

            for (Orden ordenes : listadoDeOrdenes_porPrestador) {

                modelo.addRow(new Object[]{ordenes.getIdOrden(), ordenes.getFecha(), ordenes.getFormaPago(), ordenes.getImporte(), ordenes.getAfiliado().getIdAfiliado(), ordenes.getPrestador().getIdPrestador()});
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(null, "¡Verifique los campos!");
        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(null, "¡Debe ingresar el apellido del prestador activo!");
        }
    }//GEN-LAST:event_radio_mostrarPorPrestadorActionPerformed

    private void button_ordenesPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ordenesPorFechaActionPerformed
        
        try {
            LocalDate fecha = jDateChooser_fecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            borrarFilas();
            ArrayList<Orden> listadoDeOrdenes_porFecha = orden_data.Orden_EmitidaPorFecha(fecha);
            for (Orden ordenes : listadoDeOrdenes_porFecha) {

                modelo.addRow(new Object[]{ordenes.getIdOrden(), ordenes.getFecha(), ordenes.getFormaPago(), ordenes.getImporte(), ordenes.getAfiliado().getIdAfiliado(), ordenes.getPrestador().getIdPrestador()});
            }
        } catch (NullPointerException np) {
            JOptionPane.showMessageDialog(null, "¡Debe ingresar una Fecha!");
        }
    }//GEN-LAST:event_button_ordenesPorFechaActionPerformed

    private void button_eliminarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_eliminarOrdenActionPerformed
       
        int filaSeleccionada = table_ordenes.getSelectedRow();
        if (filaSeleccionada != -1) {

            int idAfiliado = (Integer) modelo.getValueAt(filaSeleccionada, 4);

            int idPrestador = (Integer) modelo.getValueAt(filaSeleccionada, 5);

            orden_data.eliminarOrden(idAfiliado, idPrestador);

            modelo.removeRow(filaSeleccionada);

        } else {
            
            JOptionPane.showMessageDialog(null, "¡Debe seleccionar una fila!");
        }
        modelo.fireTableDataChanged();

    }//GEN-LAST:event_button_eliminarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVerOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVerOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVerOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVerOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVerOrdenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_atras;
    private javax.swing.JButton button_eliminarOrden;
    private javax.swing.JButton button_ordenesPorFecha;
    private javax.swing.JButton button_salir;
    private com.toedter.calendar.JDateChooser jDateChooser_fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JRadioButton radio_mostrarPorAfiliado;
    private javax.swing.JRadioButton radio_mostrarPorPrestador;
    private javax.swing.JTable table_ordenes;
    private javax.swing.JTextField txt_Afiliado_Prestador;
    // End of variables declaration//GEN-END:variables
}
